# Generated by Django 2.0 on 2018-03-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rzuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couser', models.CharField(max_length=30, unique=True, verbose_name='学信网账号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('men', '男'), ('women', '女')], default='men', max_length=10, verbose_name='性别')),
                ('sctime', models.DateField(verbose_name='入学时间')),
                ('pubtime', models.DateField(auto_now_add=True, verbose_name='提交时间')),
                ('iscode', models.CharField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核未通过')], default=0, max_length=10, verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '认证信息',
                'verbose_name_plural': '认证信息',
                'ordering': ['-pubtime'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
        migrations.AddField(
            model_name='rzuser',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renzheng.School', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='rzuser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renzheng.User', verbose_name='账户'),
        ),
    ]
