# Generated by Django 2.0 on 2018-03-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renzheng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzuser',
            name='iscode',
            field=models.CharField(choices=[('0', '审核中'), ('1', '审核通过'), ('2', '审核未通过')], default='0', max_length=10, verbose_name='审核状态'),
        ),
    ]
