# Generated by Django 2.0 on 2018-03-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renzheng', '0002_auto_20180309_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzuser',
            name='sctime',
            field=models.DateField(blank=True, null=True, verbose_name='入学时间'),
        ),
    ]
