# Generated by Django 2.0 on 2018-03-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renzheng', '0004_auto_20180309_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzuser',
            name='iscode',
            field=models.IntegerField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核未通过')], default=0, verbose_name='审核状态'),
        ),
    ]
